# Generated by Django 4.2 on 2025-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_doctor_appoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
