# Generated by Django 6.0 on 2026-03-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
