# Generated by Django 6.0 on 2026-04-04 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_doctor_image_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
